name: dom_builder
description: Generate and manipulate DOM elements (virtual or real), DSX (like JSX) and HTML declarations (Web and Native support).
version: 3.0.5
homepage: https://github.com/gmpassos/dom_builder

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  web_utils: ^1.0.21
  js_interop_utils: ^1.0.9
  html: ^0.15.6
  swiss_knife: ^3.3.9
  collection: ^1.19.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.3
  dependency_validator: ^4.1.3
  coverage: ^1.15.0
  web: ^1.1.1

#dependency_overrides:
#  web_utils:
#    path: ../web_utils
#  js_interop_utils:
#    path: ../js_interop_utils
#  swiss_knife:
#    path: ../swiss_knife
